spring.application.name=shopping-cart

spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_cart
spring.datasource.username=postgres
spring.datasource.password=1234

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update